<?php
/**
 * @file
 * Provides an admin interface for managing recipes.
 */

/**
 * Implements hook_permission().
 */
function recipes_permission() {
  return array(
    'access recipes overview' =>  array(
      'title' => t('Manage recipes'),
      'description' => t('Access the recipes overview page.'),
    ),
    'manage recipes' =>  array(
      'title' => t('Manage recipes'),
      'description' => t('Enable, Disable, and Revert recipes.'),
    ),
    /*
    'inspect recipes' =>  array(
      'title' => t('Inspect recipes'),
      'description' => t('View and manage the technical deails of a recipe.'),
      'restrict access' => TRUE,
      'warning' => t('People who can inspect recipes will also be able to delete individual config files.'),
    ),
    */
  );
}

/**
 * Implements hook_menu().
 */
function recipes_menu() {
  $items['admin/structure/recipes'] = array(
    'title' => 'Recipes',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('recipes_admin'),
    'access arguments' => array('access recipes overview'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'recipes.admin.inc',
  );

  // Add a menu callback for each action.
  $actions = recipes_actions_get_info();
  foreach ($actions as $action_key => $action_info) {
    $form_id = $action_info['callback'];
    $items['admin/structure/recipes/' . $action_key . '/%recipe'] = array(
      'title' => 'Recipes ' . $action_info['label'],
      'page callback' => 'backdrop_get_form',
      'page arguments' => array($form_id, 4),
      'access arguments' => array($action_info['permission']),
      'type' => MENU_NORMAL_ITEM,
      'file' => $action_info['file'],
    );
  }

  return $items;
}

/**
 * Magic loader: Loads recipe information.
 */
function recipe_load($project) {
  $modules = system_rebuild_module_data();
  return array(
    'machine_name' => $project,
    'label' => $modules[$project]->info['name'],
  );
}

/**
 * Implements hook_theme().
 */
function recipes_theme() {
  return array(
    'recipes_fieldset' => array(
      'render element' => 'form',
      'file' => 'recipes.theme.inc',
    ),
  );
}

/**
 * Retrieves a single action's info by its name, or all actions
 *
 * @param (string) $action
 *   The key of the recipe action to retrieve.
 */
function recipes_actions_get_info($action = NULL) {
  $actions = &backdrop_static(__FUNCTION__);

  if (!isset($actions)) {
    $actions = array();
    foreach (module_implements('recipes_action_info') as $module) {
      $all_actions = module_invoke($module, 'recipes_action_info');
      foreach ($all_actions as $action_key => $action_info) {
        $action_info += array(
          'module' => $module,
          'callback' => $action_key . '_form',
          'permission' => 'manage recipes',
          'requirements_callback' => 'recipes_requirements_true',
        );
        $actions[$action_key] = $action_info;
      }
    }
    backdrop_alter('recipes_action_info', $actions);
    //backdrop_sort($actions);
  }

  if (!isset($action)) {
    return $actions;
  }
  elseif (is_array($actions) && isset($actions[$action])) {
    return $actions[$action];
  }
  else {
    return FALSE;
  }
}

/**
 * Default requirements callback, always TRUE.
 */
function recipes_requirements_true() {
  return TRUE;
}

/**
 * Requirements callback: Requires the module to be enabled.
 *
 * @param string $module
 *   Machine name of the recipe module this action is to be performed on.
 *
 * @return bool
 */
function recipes_requirements_module_enabled($module) {
  if (module_exists($module)) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Requirements callback: Requires the module to be disabled.
 *
 * @param string $module
 *   Machine name of the recipe module this action is to be performed on.
 *
 * @return bool
 */
function recipes_requirements_module_disabled($module) {
  if (module_exists($module)) {
    return FALSE;
  }
  return TRUE;
}

/**
 * Implements hook_recipes_action_info().
 */
function recipes_recipes_action_info() {
  $operations = array(
    'import' => array(
      'label' => 'Enable',
      'callback' => 'recipes_import_form',
      'requirements_callback' => 'recipes_requirements_module_disabled',
      'permission' => array('manage recipes'),
      'file' => 'recipes.actions.inc',
    ),
    'inspect' => array(
      'label' => t('View'),
      'callback' => 'recipes_inspect_form',
      'permission' => array('manage recipes'),
      'file' => 'recipes.actions.inc',
    ),
    'revert' => array(
      'label' => 'Revert',
      'callback' => 'recipes_revert_form',
      'requirements_callback' => 'recipes_requirements_module_enabled',
      'permission' => array('manage recipes'),
      'file' => 'recipes.actions.inc',
    ),
    'remove' => array(
      'label' => t('Uninstall'),
      //'label' => t('Remove'),
      'callback' => 'recipes_remove_form',
      'requirements_callback' => 'recipes_requirements_module_enabled',
      'permission' => array('manage recipes'),
      'file' => 'recipes.actions.inc',
    ),
    /*
    'export' => array(
      'label' => t('Export / Extract'),
      'callback' => 'recipes_export_form',
      'requirements_callback' => 'recipes_requirements_module_enabled',
      'permission' => array('manage recipes'),
      'file' => 'recipes.actions.inc',
    ),*/
  );

  return $operations;
}
